# Generated by Django 4.1.7 on 2023-03-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_reportcomment_project_reportproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avg_rate',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
